default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['PG_DATABASE_USERNAME'] %>
  password: <%= ENV['PG_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: tzy-blog_dev

test:
  <<: *default
  database: tzy-blog_test

production:
  <<: *default
  database: tzy-blog_production
